# Generated by Django 5.0.6 on 2026-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faqentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
    ]
