/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3B82F6',
        secondary: '#10B981',
        accent: '#F59E0B',
        danger: '#EF4444',
      },
      spacing: {
        '128': '32rem',
      },
      borderRadius: {
        'xl': '1rem',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-blue-600',
    'bg-blue-800',
    'bg-gray-50',
    'bg-white',
    'text-white',
    'text-blue-600',
    'text-gray-600',
    'text-3xl',
    'text-xl',
    'text-lg',
    'font-bold',
    'px-8',
    'py-3',
    'py-16',
    'py-20',
    'rounded',
    'rounded-lg',
    'shadow-md',
    'shadow-lg',
    'hover:shadow-lg',
    'hover:bg-gray-100',
    'hover:bg-blue-900',
    'transition',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-4',
    'gap-8',
    'gap-4',
    'mb-4',
    'mb-8',
    'mb-12',
    'mb-2',
    'text-center',
    'container',
    'mx-auto',
    'px-4',
    'inline-block',
    'flex',
    'justify-center',
    'items-center',
    'text-5xl',
  ],
}