# Generated by Django 5.0.6 on 2026-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_last_product_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sender_id', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instagram_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
