# Generated by Django 5.0.6 on 2026-06-16 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_last_product_data'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='complaint_issue_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='conversation',
            name='complaint_order_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='complaint_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_order_confirmation', 'Awaiting Order Confirmation'), ('awaiting_description', 'Awaiting Description')], default='idle', max_length=40),
        ),
        migrations.AddField(
            model_name='conversation',
            name='complaint_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_conversations', to='support.supportticket'),
        ),
    ]
